### PR TITLE
KV - Profile Picture Retains After The App Reloads

### LINKED ISSUE #116: Issue "Profile Picture Bug"
The profile picture disappears when the app is reloaded. Now the user's profile screen is saved!

- [x] There is a default profile picture
- [x] The profile picture is saved

### PR DESCRIPTION
**Pull request by kenisha-v**
This PR adds functionality to allow users to save their profile pictures in the ProfileScreen component, ensuring the image persists even after the app is reloaded. I also added a default profile picture.

Simulator Screenshot - iPhone 16 Pro Max - 2024-11-20 at 16 41 03

Default Profile Picture:
Simulator Screenshot - iPhone 16 Pro Max - 2024-11-20 at 16 41 49

Closes #116

### CODE REVIEW

**Comment by lawrencewang30** [comment]
the outline for the default profile picture isn't fully aligned in my account

**Comment by kenisha-v** [comment]
Could you show me a screenshot of how the default profile picture looks like for you please

**Comment by lawrencewang30** [comment]
ProfileIconNotAligned

**Comment by kenisha-v** [comment]
It should be aligned now!

**Comment by lawrencewang30** [comment]
LGTM!

**Pull request merged**
