### PR TITLE
Now displaying (You) on the bill split screen

### LINKED ISSUE #139: Issue "Bill Splitting" #3: Adding a (You) to your username
- [ ] When splitting the bill, it will display the users you select including yourself to put a custom price
- [ ] Rather than displaying your username, it may be easier to display (You) in parentheses after your username to better help the user recognize the price they should assign themselves

### PR DESCRIPTION
**Pull request by amisra0**
Now when you split a bill and select the members, your username will have a (You) after it for clarity.
Closes #139

### CODE REVIEW

**Comment by kenisha-v** [comment]
Where exactly is the "you" supposed to be? While choosing what members, the user's own username isn't supposed to show up so I'm a bit confused

**Comment by amisra0** [comment]
> Where exactly is the "you" supposed to be? While choosing what members, the user's own username isn't supposed to show up so I'm a bit confused

Yeah, the user's own username doesn't show up there but once selecting the members when going to the page where you assign custom bill split amt, the user's own username has to show up so they can assign themselves an amount, so I added the (You) for clarity at that step.

**Comment by lawrencewang30** [comment]
The (You) is showing up for me, LGTM!

**Review by lawrencewang30 — APPROVED** [review]
LGTM

**Review by kenisha-v — APPROVED** [review]
LGTM!

**Pull request merged**
