### PR TITLE
LW - Record Payment Functionality Set Up

### PR DESCRIPTION
**Pull request by lawrencewang30**
- Record Payment functionality is working, shows correct amounts of debt respective users will have with other people in the household
- List now sorted based on most recent transactions, show both items split and repayments
- 
TransactionHistory

### CODE REVIEW

**Comment by kenisha-v** [comment]
I paid $2 once but it is showing up multiple times
Screenshot 2024-11-18 at 11 41 26 PM


And when I tried to pay $45, it showed a bunch of different transactions as well
Screenshot 2024-11-18 at 11 42 07 PM

**Comment by lawrencewang30** [comment]
I deleted the balances documents because I modified it, maybe thats the error? I would try doing this either with a new household or reset the balance documents in your current household?

**Comment by kenisha-v** [comment]
Oh perfect, it works on the new household! Also do you want to keep the container sizes different for the repayment or the same size as the other transactions? Other than that, everything is working fine

**Comment by lawrencewang30** [comment]
We can modify it for UI purposes, but that can be a later issue once our apps functionality is fully set up

**Comment by kenisha-v** [comment]
Perfect, LGTM! we can merge this branch

**Pull request merged**
