### PR TITLE
Kv - balances

### PR DESCRIPTION
**Pull request by kenisha-v**
## PR Title: Access to Transaction History and Household Balance Updates

- Users can now access their transaction history for each household.
- When an item is split, it is automatically removed from the grocery list.
- Added a balance summary to display who owes whom and how much.

### Testing Notes

- **Create a New Household**: Some database changes were made to enable households to carry total balances, so it's recommended to create a new household for testing.
- **Splitting Items**: Ensure items are split between two or more people. Note that balances won't appear if an item is split only with yourself, as you technically do not owe yourself.

### Known Issues

- The **"Record Payment" button** is not functional yet.
- An icon for the balances tab will be added soon.

closing, #104 #103 #102  #66 

### Screenshot

This is what it should look like:

Screenshot 2024-11-12 at 12 41 38 PM

### CODE REVIEW

**Comment by lawrencewang30** [comment]
UI looks good, but I have issues with the splitting logic (my PR should have fixed that since in there user can only split when household > 1)

**Comment by kenisha-v** [comment]
> UI looks good, but I have issues with the splitting logic (my PR should have fixed that since in there user can only split when household > 1)

wait so what do you want me to change in my code exactly

**Comment by lawrencewang30** [comment]
I dont think there's anything to change, we can push both branches it should be ok

**Comment by lawrencewang30** [comment]
Actually I think there may need to be a modification with the split bill function you currently have in HomeScreen.js. Since I updated it so when the user wants to split bill the list shows just the users they can split, it will not show their own name. Therefore the total split right now does not include the user, which is why I was getting the actual total cost in the Balance page

**Comment by kenisha-v** [comment]
Should I just merge your branch first then I can edit my code since I made some edits to how the split bill function works entirely?

**Comment by lawrencewang30** [comment]
yeah you can do that that should be fine

**Comment by lawrencewang30** [comment]
LGTM

**Pull request merged**
